version: '2'
services:
    channels: 
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        ports: 
            - '8000:8000'
    redis:
        image: redis
        ports:
            - '6378:6379'
